# SPDX-License-Identifier: Apache-2.0
"""Offline reference: replay tau2-bench airline trajectories through the
real ``GuardEngine``, entirely offline, no API key, no network, no live
model calls.

Run as ``python -m capsule_ledger.examples.tau2_airline_reference --all``.

**What this replays.** Five committed datasets under
``examples/data/tau2_airline/`` (see that directory's ``PROVENANCE.json``):
four are tau2-bench's own committed 4-trial airline results (trial 0, all
50 tasks) for claude-3-7-sonnet, gpt-4.1, gpt-4.1-mini and o4-mini; the
fifth is record-grounding-bench's pilot-1 -- a real 24-task shift run
against a live ``vertex_ai/gemini-2.5-flash`` agent (``docs/pilot-
1-report.md`` in that repo). None of these were generated by this repo or
for this reference -- they're real recorded/replayed transcripts, vendored
and replayed here, not synthesized to make a demo look good.

**What "replay" means here.** For every ``cancel_reservation`` and
``update_reservation_flights`` tool call in a dataset, this module
re-derives the reservation's pre-call state from the most recent prior
``get_reservation_details`` result *for the same reservation_id, within the
same task* -- exactly what a stranger with only the tool-call log (no live
DB access) could do -- and evaluates two of tau2-bench airline's real
``policy.md`` rules against it:

- ``cancel_reservation``: cancellable if booked within 24h or business
  cabin (narrowed -- see ``_cancel_eligibility``'s docstring).
- ``update_reservation_flights``: refused outright if the reservation is
  basic economy ("Basic economy flights cannot be modified.").

Every replayed action goes through a real ``GuardEngine.check()`` and
produces a real, chained, signed capsule -- the same mandate-citation
mechanism record-grounding-bench's own ``ManifestClassifier`` uses (cite a
real ledger capsule on a pass, a dangling id on a fail, so
``verify_before_dispatch`` is what actually denies it, not this module
deciding unilaterally). This module has no dependency on
record-grounding-bench -- it re-derives the same two predicates directly
from tau2-bench's public ``policy.md`` text, independently, scoped to only
what this reference needs.

**Why only two tools, not all six airline WRITE tools.** These two are the
ones whose eligibility this reference can mechanically evaluate and that
produce real refusals in the vendored data. ``book_reservation``,
``send_certificate``, ``update_reservation_baggages`` and
``update_reservation_passengers`` are out of scope for this reference
(no capsule is emitted for them) -- widening coverage to all six is real,
separate follow-up work, not silently done here.

**Why some calls come back MAPPABLE-WITH-INSTRUMENTATION, not allow/deny.**
When no prior ``get_reservation_details`` exists for a call's
``reservation_id`` within the same task, this reference has no mechanical
way to know whether the call was eligible -- it is not entitled to guess.
Rather than defaulting to allow (silently trusting an ungated call) or deny
(inventing a policy violation that was never checked), the action goes
through with no citation (``verify_before_dispatch`` is then correctly
"n/a", not "fail") and is flagged in this module's own summary and in the
capsule's ``extra.predicate_evaluable`` field: the record honestly states a
capability gap -- "this decision ran ungated because no snapshot connector
covered it" -- instead of a false pass. This is real: it happens
unforced in the vendored o4-mini and gpt-4.1 data (see the printed summary).

**Datasets are never blended.** Each dataset gets its own developer
identity, its own signing key, its own independent capsule chain, and its
own row in the summary table -- comparing refusal/instrumentation counts
*across* datasets is the point (same 50 tasks, different models, same two
predicates), but there is no single combined number.

**Retail, live model calls, and cross-task agent memory are explicitly out
of scope for this reference** -- vendoring already-run data offline is the
whole point; a live-inference or retail-domain reference is real, separate
follow-up work (see ``docs/reference/tau2-airline-reference.md``).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import capsule_emit

from capsule_ledger.folds.loader import load_definition_file
from capsule_ledger.guards import Action, GuardEngine, LocalSigner
from capsule_ledger.ledger import LedgerAPI, LedgerRecord, LedgerStore

__all__ = ["DATASETS", "DatasetResult", "run_dataset", "main"]

CATALOG_DIR = Path(__file__).resolve().parent.parent / "folds" / "catalog_defs"
DATA_DIR = Path(__file__).resolve().parent / "data" / "tau2_airline"

OPERATOR = "tau2-airline-reference"

DATASETS: dict[str, Path] = {
    "pilot1-gemini-2-5-flash": DATA_DIR / "pilot1_live_gemini-2-5-flash_airline_shift1.jsonl",
    "tau2-claude-3-7-sonnet": DATA_DIR / "tau2_committed_claude-3-7-sonnet_airline_trial0.jsonl",
    "tau2-gpt-4-1": DATA_DIR / "tau2_committed_gpt-4-1_airline_trial0.jsonl",
    "tau2-gpt-4-1-mini": DATA_DIR / "tau2_committed_gpt-4-1-mini_airline_trial0.jsonl",
    "tau2-o4-mini": DATA_DIR / "tau2_committed_o4-mini_airline_trial0.jsonl",
}

_SIM_NOW = "2024-05-15T15:00:00"  # tau2 airline's fixed simulated "now" (both datasets' tasks are set here)
_RULE_TOOLS = {"cancel_reservation", "update_reservation_flights"}
_ACTION_CLASS = {"cancel_reservation": "booking.cancel", "update_reservation_flights": "booking.modify"}


@dataclass(frozen=True)
class PredicateVerdict:
    passed: bool
    reason: str
    instrumentation_gap: bool = False


def _within_24h(created_at: str | None) -> bool | None:
    from datetime import datetime

    if not created_at:
        return None
    try:
        delta = datetime.fromisoformat(_SIM_NOW) - datetime.fromisoformat(created_at)
    except ValueError:
        return None
    return delta.total_seconds() <= 24 * 3600


def _cancel_eligibility(snapshot: dict | None) -> PredicateVerdict:
    """tau2-bench airline ``policy.md``, "Cancel flight": cancellable if
    booked within 24h, OR airline-cancelled, OR business cabin, OR
    insurance-covered-per-stated-reason.

    **Narrowed, same as record-grounding-bench's own v1 manifest**: the
    airline-cancelled and insurance-covered paths need state
    (``get_reservation_details`` doesn't carry per-flight-date cancellation
    status, and the insurance-covered path depends on the *stated reason*
    for the call, which isn't tool-call-level data at all) this reference
    doesn't have from the log alone. Checks only booked-within-24h and
    business-cabin -- the two paths mechanically recoverable from a prior
    ``get_reservation_details`` result. A reservation legitimately
    cancellable only via the narrowed-out paths is scored ``passed=False``
    here; that is this reference's own known scope limit, stated plainly,
    not a claim that tau2-bench's guard is wrong.
    """
    if snapshot is None:
        return PredicateVerdict(
            False,
            "no prior get_reservation_details for this reservation_id in the replayed log -- "
            "eligibility cannot be evaluated without a live DB read or an instrumented snapshot connector",
            instrumentation_gap=True,
        )
    if snapshot.get("cabin") == "business":
        return PredicateVerdict(True, "business cabin reservation")
    within_24h = _within_24h(snapshot.get("created_at"))
    if within_24h:
        return PredicateVerdict(True, "booked within the last 24 hours")
    return PredicateVerdict(
        False,
        f"not booked within 24h and not business cabin (cabin={snapshot.get('cabin')!r}, "
        f"created_at={snapshot.get('created_at')!r})",
    )


def _no_basic_economy_modification(snapshot: dict | None) -> PredicateVerdict:
    """tau2-bench airline ``policy.md``, "Modify flight": "Basic economy
    flights cannot be modified." """
    if snapshot is None:
        return PredicateVerdict(
            False,
            "no prior get_reservation_details for this reservation_id in the replayed log -- "
            "eligibility cannot be evaluated without a live DB read or an instrumented snapshot connector",
            instrumentation_gap=True,
        )
    if snapshot.get("cabin") == "basic_economy":
        return PredicateVerdict(False, "reservation is basic economy -- flights cannot be modified")
    return PredicateVerdict(True, f"cabin={snapshot.get('cabin')!r}, not basic economy")


_PREDICATES = {
    "cancel_reservation": _cancel_eligibility,
    "update_reservation_flights": _no_basic_economy_modification,
}


@dataclass(frozen=True)
class ReplayedCall:
    task_id: str
    call_seq: int
    tool_name: str
    reservation_id: str | None
    verdict: str  # "ALLOW" | "DENY" | "MAPPABLE-WITH-INSTRUMENTATION"
    reason: str
    capsule_id: str
    outcome: str  # the guard's own ALLOW/DENY/ESCALATE


@dataclass(frozen=True)
class DatasetResult:
    dataset: str
    records: tuple[LedgerRecord, ...]
    calls: tuple[ReplayedCall, ...]

    def counts(self) -> dict[str, int]:
        counts = {"ALLOW": 0, "DENY": 0, "MAPPABLE-WITH-INSTRUMENTATION": 0}
        for call in self.calls:
            counts[call.verdict] += 1
        return counts


def _seeded_secret(dataset: str) -> bytes:
    return hashlib.sha256(f"tau2-airline-reference/{dataset}".encode()).digest()


def _iter_task_events(path: Path):
    """Yield (task_id, [event_dict, ...]) in file order, one group per
    span_start/span_end pair. Non-tool_call lines outside a span are
    ignored (there shouldn't be any)."""
    current_task: str | None = None
    current_events: list[dict] = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            kind = rec.get("kind")
            if kind == "span_start":
                current_task = rec["task_id"]
                current_events = []
            elif kind == "tool_call":
                current_events.append(rec)
            elif kind == "span_end":
                yield current_task, current_events
                current_task, current_events = None, []


def _mandate_capsule_id(
    ledger: LedgerAPI, *, operator: str, developer: str, tool_name: str, action_class: str,
    task_id: str, call_seq: int, verdict: PredicateVerdict,
) -> str | None:
    if not verdict.passed:
        # Deliberately dangling: verify_before_dispatch's ledger.fetch()
        # returns None for this id, which is what actually denies the
        # action -- this module never denies unilaterally.
        return f"policy-check-failed/{action_class}/{task_id}/{call_seq}"
    result = capsule_emit.emit(
        action=f"policy_check.{action_class}",
        operator=operator,
        developer=developer,
        agent_input={"tool_name": tool_name, "tau2_task_id": task_id, "tau2_call_seq": call_seq},
        agent_output={"policy_check_passed": True, "reason": verdict.reason},
        verdict="confirmed",
        effect={"type": f"policy_check.{action_class}", "status": "confirmed"},
        decision="accept",
        action_type="fyi",
        anchor=False,
        ledger=os.devnull,
    ).capsule
    ledger.append(result, consequential=False)
    return result["capsule_id"]


def run_dataset(dataset: str, path: Path, *, store_dir: str | os.PathLike | None = None) -> DatasetResult:
    """Replay one vendored dataset end to end against a fresh, ephemeral,
    local ``LedgerStore``. Fully offline: no network, no API key."""
    cleanup_dir: Path | None = None
    if store_dir is None:
        store_dir = tempfile.mkdtemp(prefix=f"capsule-ledger-tau2-airline-{dataset}-")
        cleanup_dir = Path(store_dir)
    ledger = LedgerStore(store_dir)
    try:
        caps_fold = load_definition_file(CATALOG_DIR / "spend.weekly.yaml")
        signer = LocalSigner(key_id=f"tau2-airline-reference-{dataset}", secret=_seeded_secret(dataset))
        engine = GuardEngine(ledger=ledger, caps_fold=caps_fold, signer_provider=lambda: signer)
        developer = f"tau2-airline-reference@{dataset}"

        calls: list[ReplayedCall] = []
        last_capsule_id: str | None = None
        for task_id, events in _iter_task_events(path):
            snapshots: dict[str, dict] = {}
            for call_seq, event in enumerate(events):
                tool_name = event["tool_name"]
                if tool_name == "get_reservation_details" and not event["error"]:
                    try:
                        parsed = json.loads(event["result_content"])
                    except (TypeError, json.JSONDecodeError):
                        parsed = None
                    if isinstance(parsed, dict) and parsed.get("reservation_id"):
                        snapshots[parsed["reservation_id"]] = parsed
                if tool_name not in _RULE_TOOLS:
                    continue

                reservation_id = (event.get("arguments") or {}).get("reservation_id")
                snapshot = snapshots.get(reservation_id) if reservation_id else None
                verdict = _PREDICATES[tool_name](snapshot)
                action_class = _ACTION_CLASS[tool_name]

                cited = None
                if not verdict.instrumentation_gap:
                    cited = _mandate_capsule_id(
                        ledger, operator=OPERATOR, developer=developer, tool_name=tool_name,
                        action_class=action_class, task_id=task_id, call_seq=call_seq, verdict=verdict,
                    )

                action = Action(
                    verb=tool_name,
                    operator=OPERATOR,
                    developer=developer,
                    action_class=action_class,
                    action_id=f"{tool_name}/{dataset}/{task_id}/{call_seq}",
                    timestamp=event.get("timestamp"),
                    target=reservation_id,
                    cited_mandate_capsule_id=cited,
                    extra={
                        "tau2_task_id": task_id,
                        "tau2_call_seq": call_seq,
                        "predicate_evaluable": not verdict.instrumentation_gap,
                        "predicate_reason": verdict.reason,
                    },
                )
                decision = engine.check(action, chain_parent=last_capsule_id, chain_relation="follows")
                if decision.capsule is not None:
                    last_capsule_id = decision.capsule["capsule_id"]
                    capsule_id = last_capsule_id
                else:
                    capsule_id = decision.outcome

                if verdict.instrumentation_gap:
                    label = "MAPPABLE-WITH-INSTRUMENTATION"
                elif verdict.passed:
                    label = "ALLOW"
                else:
                    label = "DENY"
                calls.append(
                    ReplayedCall(
                        task_id=task_id, call_seq=call_seq, tool_name=tool_name,
                        reservation_id=reservation_id, verdict=label, reason=verdict.reason,
                        capsule_id=capsule_id, outcome=decision.outcome,
                    )
                )

        records = tuple(ledger.scan())
        return DatasetResult(dataset=dataset, records=records, calls=tuple(calls))
    finally:
        ledger.close()
        if cleanup_dir is not None:
            shutil.rmtree(cleanup_dir, ignore_errors=True)


def _export_fixture(records: tuple[LedgerRecord, ...], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for record in records:
            fh.write(json.dumps(record.capsule, separators=(",", ":")) + "\n")


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="python -m capsule_ledger.examples.tau2_airline_reference",
        description="Offline replay of tau2-bench airline trajectories through the real GuardEngine "
        "(see module docstring). No API key, no network, no live model calls.",
    )
    parser.add_argument("--dataset", choices=sorted(DATASETS), help="replay one dataset (default: --all)")
    parser.add_argument("--all", action="store_true", help="replay every dataset and print a comparison table")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="directory to write one <dataset>.jsonl ledger fixture per replayed dataset "
        "(default: print a summary only, write nothing)",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    if not args.dataset and not args.all:
        args.all = True
    targets = sorted(DATASETS) if args.all else [args.dataset]

    print(f"{'dataset':<26} {'ALLOW':>6} {'DENY':>6} {'WITH-INSTRUMENTATION':>22}   sample refusal capsule")
    for dataset in targets:
        result = run_dataset(dataset, DATASETS[dataset])
        counts = result.counts()
        sample = next((c for c in result.calls if c.verdict == "DENY"), None)
        sample_txt = f"{sample.capsule_id[:16]}… ({sample.tool_name}, task {sample.task_id})" if sample else "-"
        print(
            f"{dataset:<26} {counts['ALLOW']:>6} {counts['DENY']:>6} "
            f"{counts['MAPPABLE-WITH-INSTRUMENTATION']:>22}   {sample_txt}"
        )
        if args.out_dir:
            out_path = Path(args.out_dir) / f"{dataset}.jsonl"
            _export_fixture(result.records, out_path)
            print(f"  -> {len(result.records)} capsule(s) written to {out_path}")
            with_instr = next((c for c in result.calls if c.verdict == "MAPPABLE-WITH-INSTRUMENTATION"), None)
            if with_instr:
                print(
                    f"  -> WITH-INSTRUMENTATION example: capsule {with_instr.capsule_id[:16]}… "
                    f"({with_instr.tool_name}, task {with_instr.task_id}): {with_instr.reason}"
                )
            if sample:
                print(
                    f"  -> verify one row offline:  capsule verify {sample.capsule_id} --ledger {out_path}"
                )
    print(
        "\nCounts are never blended across datasets -- each row is one model's own replay against "
        "the same two policy predicates. See docs/reference/tau2-airline-reference.md."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
