# SPDX-License-Identifier: Apache-2.0
"""Dry-run report data shapes.

These carry only what the design's headline folds / per-guard tables / the
single "most consequential" callout need. Every field here is either read
straight off a real ``GuardDecision`` (T3) or computed from one — nothing in
this module invents a number; see ``build.py`` for where each field comes
from.
"""
from __future__ import annotations

from dataclasses import dataclass, field

__all__ = ["ReportRow", "GuardSection", "ModelNote", "DryRunReport"]


@dataclass(frozen=True)
class ReportRow:
    """One would-have-held decision, attributed to the guard whose
    constraint failed it. ``capsule`` is this decision's own sealed capsule
    (dry_run decisions are still built, signed, and appended to the guard's
    own replay-local view — see ``docs/failure-semantics.md``'s "an unsigned
    record is not a record" and ``engine.py``'s dry_run handling). ``cited_capsule``
    is the prior record this row's check matched against (e.g. the earlier
    payment a dedupe hit repeats), when the check produced one — carried in
    full so the browser can re-verify it, not just display its id.
    """

    when: str
    agent: str
    why: str
    capsule: dict
    amount_minor: int | None = None
    currency: str | None = None
    cited_capsule_id: str | None = None
    cited_capsule: dict | None = None

    @property
    def fingerprint(self) -> str:
        capsule_id = self.capsule.get("capsule_id", "")
        return capsule_id[:8] + "…" if capsule_id else ""


@dataclass(frozen=True)
class GuardSection:
    guard_id: str
    what: str
    rows: tuple[ReportRow, ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class ModelNote:
    """Optional, operator-supplied model commentary. Never generated by this
    module — see ``build.py``'s docstring. Omitted entirely (``None``) is the
    default and fully supported path."""

    quote: str
    model_id: str
    record_count: int


@dataclass(frozen=True)
class DryRunReport:
    operator: str
    agents: tuple[str, ...]
    since_label: str | None
    actions_replayed: int
    record_range: tuple[int, int]
    checkpoint: int
    guards: tuple[GuardSection, ...]
    replay_command: str
    generated_at: str
    model_note: ModelNote | None = None
    # The active policy manifest's own digest (``asg_ledger.policy``), when
    # one was resolved for this replay -- "evaluated under manifest <digest>"
    # (see ``cli/guard_cmds.py``). ``None`` when no manifest was configured.
    manifest_digest: str | None = None

    @property
    def held_rows(self) -> list[tuple[str, ReportRow]]:
        return [(section.guard_id, row) for section in self.guards for row in section.rows]

    @property
    def would_have_held_count(self) -> int:
        return len(self.held_rows)

    def consequential(self) -> tuple[str, ReportRow] | None:
        """The single highest-amount would-have-held row, across all guards.

        A pick, never a sum -- money in different currencies is never added
        together (see ``value_held_label`` in ``build.py``)."""
        candidates = [(g, r) for g, r in self.held_rows if r.amount_minor is not None]
        if not candidates:
            return self.held_rows[0] if self.held_rows else None
        return max(candidates, key=lambda gr: gr[1].amount_minor)
